logging.level:
  root: ERROR
  io.mikael: DEBUG

spring.jackson.serialization.indent_output: true

spring.servlet.multipart.max-file-size: 5MB
spring.servlet.multipart.max-request-size: 5MB

app.gpu-enabled: true
app.gpu-memory-fraction: 0.25

app.model: 'classpath:deeplabv3_mnv2_pascal_trainval.pb'
#app.model: 'file:///home/mikael/devel/temp/segmentation/models/deeplabv3_pascal_trainval/frozen_inference_graph.pb'
